name: Tests
on: [push, pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v17
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn --immutable

      - name: Build dependencies
        run: yarn build

      - name: Formatting code
        run: yarn lint

      - name: Tests
        run: yarn test
